group: edge

sudo: required

language: node_js
node_js:
  - "8"
  - "10"
  - "12"

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck
      - devscripts

install:
  - npm install

script:
  - npm test

matrix:
  fast_finish: true
